### ISSUE TITLE
kwarg `ignore` was not used in `jaconv.normalize`

### ISSUE THREAD

**Issue by keeofkoo** [ikegami-yukino/jaconv#10]
Hi!
Pretty lucky to get to use this convenient tool for handling Japanese script.
Keyword argument `ignore` comes handy in some circumstances where you don't want some of the characters to stay unchanged. I just found `ignore` was not used in `jaconv.normalize`. It'd be an easy fix though.
ありがとうございます〜

**Comment by ikegami-yukino** [comment]
Thanks.
As you said, the keyword argument `ignore` is not used in `jaconv.normalize`.
Thus I think `ignore` will be deleted from `jaconv.normalize`.
