### ISSUE TITLE
日本語Readmeのサンプル

### ISSUE THREAD

**Issue by kzthrk** [ikegami-yukino/jaconv#12]
※日本語で申し訳ないですが、これを英語でというのも若干罰ゲーム感漂い、だったらスルーしちゃおうって流れになるところからのIssue作成なのでどうかご容赦を。

以下の部分の日本語が間違っていないでしょうか？

```
# ASCII以外の半角文字 to 全角文字
jaconv.h2z(u'abc', ascii=True)
# => u'ａｂｃ'

# 数字以外の半角文字 to 全角文字
jaconv.h2z(u'123', digit=True)
# => u'１２３'

```
なお、使う側からすると、混ざっている文字列に対して操作をするケースがあることを考えるとASCII以外→ASCIIのみという言い換えも良くないと思います。

というのは、kanaはデフォルトTrueで、いまのロジックだと以下のようになり、カナは常に変換されます。
```
>>> import jaconv
>>> jaconv.h2z(u'123abcﾃｨﾛ･ﾌｨﾅｰﾚ', digit=True)
'１２３abcティロ・フィナーレ'
>>> jaconv.h2z(u'123abcﾃｨﾛ･ﾌｨﾅｰﾚ', ascii=True)
'123ａｂｃティロ・フィナーレ'
>>>
```

これに関しては、英語のコメントを修正するのか、ロジックの修正なのか判断つきませんが、合わせてご判断頂ければと思います。

**Comment by ikegami-yukino** [comment]
@kzthrk 
ご指摘ありがとうございます。
引数のデフォルト値を変えると既存ユーザーが混乱してしまう可能性があるのでドキュメントのみ修正しました。

それと、`もし間違いを見つけたら、やさしく教えてください。強めに指摘されたり、叱られるとすぐにへこみます。`
